platform :ios, '7.0'
   pod 'MBProgressHUD'
   pod 'Masonry'
   pod 'IQKeyboardManager'
   pod 'REFrostedViewController'
   pod 'MJRefresh'
   pod 'MJExtension'
   pod 'AMap3DMap', '~> 2.6.1'
   pod 'AMapSearch', '~> 2.6.0'
   pod 'AMapCloudMap', '~> 1.2.0'
   pod 'OpenUDID', '~> 1.0.0'